[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pytest-markdir"
version = "0.1.0"
dependencies = [
    "pytest>=6.2,<10"
]

[project.entry-points.pytest11]
markdir = "pytest_markdir.plugin"
